//CREATE USER
POST  http://localhost:3000/api/users
content-type: application/json

{
    "firstname": "Artee",
    "lastname": "Aanchal"
}

###

//GET ALL USERS

GET http://localhost:3000/api/users
###

//GET User
GET http://localhost:3000/api/users/2

//Delete User
###
DELETE http://localhost:3000/api/users/delete/7

###

//UPDATE USER
PUT http://localhost:3000/api/users/update/1
content-type: application/json

{
    "firstname": "Ashish",
    "lastname": "pppp"
}

###
//ADD Products
POST  http://localhost:3000/api/products
content-type: application/json

{
    "name": "Jaegermeister 60ml vodka",
    "serial_number": "10699"
}

//GET PRODUCTS
###
GET http://localhost:3000/api/products



//GET PRODUCT
###
GET http://localhost:3000/api/products/1


//DELETE PRODUCT
###
DELETE http://localhost:3000/api/products/delete/1


//UPDATE PRODUCT
###
PUT http://localhost:3000/api/products/update/1
content-type: application/json

{
    "name": "Baltra fan triple blades",
    "serial_number": "144332"
}




